# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: test.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'test.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"U\n\x0bUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x04 \x01(\x08\x12\x0c\n\x04tags\x18\x05 \x03(\t\"j\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x1a\n\x04user\x18\x04 \x01(\x0b\x32\x0c.UserRequest\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\"Y\n\x0eProductRequest\x12\x14\n\x0cproduct_name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\"l\n\x0fProductResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12 \n\x07product\x18\x03 \x01(\x0b\x32\x0f.ProductRequest\x12\x13\n\x0btotal_value\x18\x04 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=14
  _globals['_USERREQUEST']._serialized_end=99
  _globals['_USERRESPONSE']._serialized_start=101
  _globals['_USERRESPONSE']._serialized_end=207
  _globals['_PRODUCTREQUEST']._serialized_start=209
  _globals['_PRODUCTREQUEST']._serialized_end=298
  _globals['_PRODUCTRESPONSE']._serialized_start=300
  _globals['_PRODUCTRESPONSE']._serialized_end=408
# @@protoc_insertion_point(module_scope)
