server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 16MB
      max-request-size: 16MB
  thymeleaf:
    cache: false

logging:
  level:
    com.proto.testing.demo: DEBUG
    root: INFO